config/routes.rb
Chowtime::Application.routes.draw do
  resources :create_recipe_categories, :kitchen_items

  resources :recipes do
    resources :ingredients, :steps, :recipe_tags, :kitchen_items
  end


  authenticated :user do
    root :to => "pages#inside", as: :authenticated_root
  end
  
  
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"

  get "/pages/styleguide/:page" => "pages#styleguide", as: "styleguide"
  get '/myIndex' => 'recipes#myIndex'
  get '/getInspired' => 'recipes#getInspired'
  get '/myKitchen' => 'kitchen_items#myKitchen'
  get '/shoppingcart' => 'kitchen_items#shoppingcart'
  
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
  end

end

app/models/recipe_tag.rb
class RecipeTag < ActiveRecord::Base
	has_and_belongs_to_many :recipes
end

app/controllers/recipe_tags_controller.rb
class RecipeTagsController < ApplicationController
  before_action :set_recipe_tag, only: [:show, :edit, :update, :destroy]

  # GET /recipe_tags
  # GET /recipe_tags.json
  def index
    @recipe_tags = RecipeTag.all
  end

  # GET /recipe_tags/1
  # GET /recipe_tags/1.json
  def show
  end

  # GET /recipe_tags/new
  def new
    @recipe_tag = RecipeTag.new
  end

  # GET /recipe_tags/1/edit
  def edit
  end

  # POST /recipe_tags
  # POST /recipe_tags.json
  def create
    @recipe_tag = RecipeTag.new(recipe_tag_params)

    respond_to do |format|
      if @recipe_tag.save
        format.html { redirect_to @recipe_tag, notice: 'Recipe tag was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_tag }
      else
        format.html { render :new }
        format.json { render json: @recipe_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_tags/1
  # PATCH/PUT /recipe_tags/1.json
  def update
    respond_to do |format|
      if @recipe_tag.update(recipe_tag_params)
        format.html { redirect_to @recipe_tag, notice: 'Recipe tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_tag }
      else
        format.html { render :edit }
        format.json { render json: @recipe_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_tags/1
  # DELETE /recipe_tags/1.json
  def destroy
    @recipe_tag.destroy
    respond_to do |format|
      format.html { redirect_to recipe_tags_url, notice: 'Recipe tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_tag
      @recipe_tag = RecipeTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_tag_params
      params.require(:recipe_tag).permit(:name, :icon, :category_id)
    end
end

app/views/recipe_tags/_form.html.erb
<%= form_for(@recipe_tag) do |f| %>
  <% if @recipe_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_tag.errors.count, "error") %> prohibited this recipe_tag from being saved:</h2>

      <ul>
      <% @recipe_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipe_tags/edit.html.erb
<h1>Editing Recipe Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe_tag %> |
<%= link_to 'Back', recipe_tags_path %>

app/views/recipe_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipe Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Icon</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_tags.each do |recipe_tag| %>
      <tr>
        <td><%= recipe_tag.name %></td>
        <td><%= recipe_tag.icon %></td>
        <td><%= recipe_tag.category_id %></td>
        <td><%= link_to 'Show', recipe_tag %></td>
        <td><%= link_to 'Edit', edit_recipe_tag_path(recipe_tag) %></td>
        <td><%= link_to 'Destroy', recipe_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe tag', new_recipe_tag_path %>

app/views/recipe_tags/new.html.erb
<h1>New Recipe Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_tags_path %>

app/views/recipe_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe_tag.name %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @recipe_tag.icon %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recipe_tag.category_id %>
</p>

<%= link_to 'Edit', edit_recipe_tag_path(@recipe_tag) %> |
<%= link_to 'Back', recipe_tags_path %>