config/routes.rb
Chowtime::Application.routes.draw do
  resources :create_recipe_categories, :kitchen_items

  resources :recipes do
    resources :ingredients, :steps, :recipe_tags, :kitchen_items
  end


  authenticated :user do
    root :to => "pages#inside", as: :authenticated_root
  end
  
  
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"

  get "/pages/styleguide/:page" => "pages#styleguide", as: "styleguide"
  get '/myIndex' => 'recipes#myIndex'
  get '/getInspired' => 'recipes#getInspired'
  get '/myKitchen' => 'kitchen_items#myKitchen'
  get '/shoppingcart' => 'kitchen_items#shoppingcart'
  
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
  end

end

app/models/create_recipe_category.rb
class CreateRecipeCategory < ActiveRecord::Base
end

app/controllers/create_recipe_categories_controller.rb
class CreateRecipeCategoriesController < ApplicationController
  before_action :set_create_recipe_category, only: [:show, :edit, :update, :destroy]

  # GET /create_recipe_categories
  # GET /create_recipe_categories.json
  def index
    @create_recipe_categories = CreateRecipeCategory.all
  end

  # GET /create_recipe_categories/1
  # GET /create_recipe_categories/1.json
  def show
  end

  # GET /create_recipe_categories/new
  def new
    @create_recipe_category = CreateRecipeCategory.new
  end

  # GET /create_recipe_categories/1/edit
  def edit
  end

  # POST /create_recipe_categories
  # POST /create_recipe_categories.json
  def create
    @create_recipe_category = CreateRecipeCategory.new(create_recipe_category_params)

    respond_to do |format|
      if @create_recipe_category.save
        format.html { redirect_to @create_recipe_category, notice: 'Create recipe category was successfully created.' }
        format.json { render :show, status: :created, location: @create_recipe_category }
      else
        format.html { render :new }
        format.json { render json: @create_recipe_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_recipe_categories/1
  # PATCH/PUT /create_recipe_categories/1.json
  def update
    respond_to do |format|
      if @create_recipe_category.update(create_recipe_category_params)
        format.html { redirect_to @create_recipe_category, notice: 'Create recipe category was successfully updated.' }
        format.json { render :show, status: :ok, location: @create_recipe_category }
      else
        format.html { render :edit }
        format.json { render json: @create_recipe_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_recipe_categories/1
  # DELETE /create_recipe_categories/1.json
  def destroy
    @create_recipe_category.destroy
    respond_to do |format|
      format.html { redirect_to create_recipe_categories_url, notice: 'Create recipe category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_recipe_category
      @create_recipe_category = CreateRecipeCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_recipe_category_params
      params.require(:create_recipe_category).permit(:name)
    end
end

app/views/create_recipe_categories/_form.html.erb
<%= form_for(@create_recipe_category) do |f| %>
  <% if @create_recipe_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@create_recipe_category.errors.count, "error") %> prohibited this create_recipe_category from being saved:</h2>

      <ul>
      <% @create_recipe_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/create_recipe_categories/edit.html.erb
<h1>Editing Create Recipe Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @create_recipe_category %> |
<%= link_to 'Back', create_recipe_categories_path %>

app/views/create_recipe_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Create Recipe Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @create_recipe_categories.each do |create_recipe_category| %>
      <tr>
        <td><%= create_recipe_category.name %></td>
        <td><%= link_to 'Show', create_recipe_category %></td>
        <td><%= link_to 'Edit', edit_create_recipe_category_path(create_recipe_category) %></td>
        <td><%= link_to 'Destroy', create_recipe_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Create recipe category', new_create_recipe_category_path %>

app/views/create_recipe_categories/new.html.erb
<h1>New Create Recipe Category</h1>

<%= render 'form' %>

<%= link_to 'Back', create_recipe_categories_path %>

app/views/create_recipe_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @create_recipe_category.name %>
</p>

<%= link_to 'Edit', edit_create_recipe_category_path(@create_recipe_category) %> |
<%= link_to 'Back', create_recipe_categories_path %>