config/routes.rb
Chowtime::Application.routes.draw do
  resources :create_recipe_categories, :kitchen_items

  resources :recipes do
    resources :ingredients, :steps, :recipe_tags, :kitchen_items
  end


  authenticated :user do
    root :to => "pages#inside", as: :authenticated_root
  end
  
  
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"

  get "/pages/styleguide/:page" => "pages#styleguide", as: "styleguide"
  get '/myIndex' => 'recipes#myIndex'
  get '/getInspired' => 'recipes#getInspired'
  get '/myKitchen' => 'kitchen_items#myKitchen'
  get '/shoppingcart' => 'kitchen_items#shoppingcart'
  
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
  end

end

app/models/kitchen_item.rb
class KitchenItem < ActiveRecord::Base
  belongs_to :user
  has_many :food_groups
end

app/controllers/kitchen_items_controller.rb
class KitchenItemsController < ApplicationController
  before_action :set_kitchen_item, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [
    :myKitchen, :shoppingcart, :create, :edit, :update, :destroy
  ]

  # GET /kitchen_items
  # GET /kitchen_items.json
  def index
    @kitchen_items = KitchenItem.all
  end

  def myKitchen
    @page_icon   = "fd-fork42"
    @page_header = "My Kitchen"

    @myItems = KitchenItem.where(:user_id => current_user.id).where(:userHas => true)
    @categories = FoodGroup.all

  end


  # GET /kitchen_items/1
  # GET /kitchen_items/1.json
  def show
  end

  # GET /shoppingCart/1
  # GET /shoppingCart/1.json
  def shoppingcart
    @page_icon   = "im-cart3"
    @page_header = "Your Shopping Cart"
    
    @categories = FoodGroup.all
    @yourcart = KitchenItem.where(:user_id => current_user.id).where(:userHas => false)
  end

  # GET /kitchen_items/new
  def new
    @kitchen_item = KitchenItem.new
    @thisUser = current_user.id
    @page_icon   = "fd-fork42"
    @page_header = "New Pantry Item"
  end

  # GET /kitchen_items/1/edit
  def edit
  end

  # POST /kitchen_items
  # POST /kitchen_items.json
  def create
    @kitchen_item = KitchenItem.new(kitchen_item_params)

    respond_to do |format|
      if @kitchen_item.save
        format.html { redirect_to @kitchen_item, notice: 'Kitchen item was successfully created.' }
        format.json { render :show, status: :created, location: @kitchen_item }
      else
        format.html { render :new }
        format.json { render json: @kitchen_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitchen_items/1
  # PATCH/PUT /kitchen_items/1.json
  def update
    respond_to do |format|
      if @kitchen_item.update(kitchen_item_params)
        format.html { redirect_to @kitchen_item, notice: 'Kitchen item was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitchen_item }
      else
        format.html { render :edit }
        format.json { render json: @kitchen_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitchen_items/1
  # DELETE /kitchen_items/1.json
  def destroy
    @kitchen_item.destroy
    respond_to do |format|
      format.html { redirect_to kitchen_items_url, notice: 'Kitchen item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitchen_item
      @kitchen_item = KitchenItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitchen_item_params
      params.permit(:name, :user_id, :userHas)
    end
end

app/views/kitchen_items/_form.html.erb
<%= form_for(@kitchen_item, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @kitchen_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitchen_item.errors.count, "error") %> prohibited this kitchen_item from being saved:</h2>

      <ul>
      <% @kitchen_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="form-group">
      <%= f.label :name, :class => "col-xs-12 col-sm-1 control-label" %>
      <div class="col-xs-12 col-sm-5">
        <%= f.text_field :name, :class => "form-control", :autofocus => "autofocus", :placeholder => "Recipe Name" %>
      </div>
    </div>
  </div>



  <div class="actions" style="margin-top:20px;">
    <%= f.submit :class => 'btn btn-success' %>
  </div>

  <div class="field" style="display:none;">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field" style="display:none;">
    <%= f.label :userHas %><br>
    <%= f.text_field :userHas %>
  </div>
<% end %>


<script>
  $('#kitchen_item_user_id').val(<%= @thisUser %>);
</script>

app/views/kitchen_items/edit.html.erb
<h1>Editing Kitchen Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @kitchen_item %> |
<%= link_to 'Back', kitchen_items_path %>

app/views/kitchen_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kitchen Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kitchen_items.each do |kitchen_item| %>
      <tr>
        <td><%= kitchen_item.name %></td>
        <td><%= kitchen_item.user %></td>
        <td><%= link_to 'Show', kitchen_item %></td>
        <td><%= link_to 'Edit', edit_kitchen_item_path(kitchen_item) %></td>
        <td><%= link_to 'Destroy', kitchen_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kitchen item', new_kitchen_item_path %>

app/views/kitchen_items/myKitchen.html.erb
<%= render 'layouts/page_header' %>

<%= stylesheet_link_tag "plugins", "data-turbolinks-track" => true %>

<% if !@myItems.empty? %>
<div class="outlet">
<div class="row">
  <div class="gallery">
    <!-- start .gallery -->
    <div class="gallery-toolbar">
      <div class="col-lg-12">
        <button class="filter btn btn-primary btn-alt mr5" data-filter="all">All</button>
        <% @categories.each do |thisCategory| %>
          <button class="filter btn btn-primary btn-alt mr5" data-filter=".<%= thisCategory.groupName.downcase %>"><%= thisCategory.groupName %></button>
        <% end %>
      </div>
    </div>
    <div class="gallery-inner">
      <% @thisArray = @myItems #Assignment for templating %>
      <%= render 'widgets/items_ingredients_tab', object: @thisArray %>
    </div>
  </div>
</div>
</div>

<% else %>
  <h4>Your kitchen is empty!</h4>
<% end %>

<br>


<%= javascript_include_tag "plugins/misc/gallery/jquery.magnific-popup.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "plugins/misc/mixitup/jquery.mixitup.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "pages/gallery", "data-turbolinks-track" => true %>
<script>
  var newButton = $('#newRecipe');
  $('.actionItems h1').append(newButton);
  newButton.slideDown();
</script>

app/views/kitchen_items/new.html.erb
<%= render 'layouts/page_header' %>

<%= render 'form' %>

app/views/kitchen_items/shoppingcart.html.erb
<%= render 'layouts/page_header' %>

<%= stylesheet_link_tag "plugins", "data-turbolinks-track" => true %>

<% if !@yourcart.empty? %>
<div class="outlet hidden-xs">
<div class="row">
  <div class="gallery">
    <!-- start .gallery -->
    <div class="gallery-toolbar">
      <div class="col-lg-12">
        <button class="filter btn btn-primary btn-alt mr5" data-filter="all">All</button>
        <% @categories.each do |thisCategory| %>
          <button class="filter btn btn-primary btn-alt mr5" data-filter=".<%= thisCategory.groupName.downcase %>"><%= thisCategory.groupName %></button>
        <% end %>
      </div>
    </div>
    <div class="gallery-inner">
      <% @thisArray = @yourcart #Assignment for templating %>
      <%= render 'widgets/items_ingredients_tab', object: @thisArray %>
    </div>
  </div>
</div>
</div>

<div class="visible-xs">
  <h4>XS View</h4>
</div>

<% else %>
  <h4>Your shopping cart is empty</h4>
<% end %>

<br>


<%= javascript_include_tag "plugins/misc/gallery/jquery.magnific-popup.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "plugins/misc/mixitup/jquery.mixitup.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "pages/gallery", "data-turbolinks-track" => true %>
<script>
  var newButton = $('#newRecipe');
  $('.actionItems h1').append(newButton);
  newButton.slideDown();
</script>

app/views/kitchen_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kitchen_item.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @kitchen_item.user %>
</p>
<p>
  <strong>User Has:</strong>
  <%= @kitchen_item.userHas %>
</p>

<%= link_to 'Edit', edit_kitchen_item_path(@kitchen_item) %> |
<%= link_to 'Back', kitchen_items_path %>